# Generated by Django 2.0.7 on 2019-07-18 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190718_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
