# Generated by Django 2.0.7 on 2019-07-22 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190718_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='dob',
            new_name='date_of_birth',
        ),
    ]
